language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - make
            - libcurl4-gnutls-dev
            - libqgpsmm-dev
            - libgps-dev
            - cppcheck
            - libcppunit-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
    - wget https://github.com/CosmicResearch/g3log/releases/download/1.3.3/g3log-Linux-x86.deb
    - sudo dpkg -i g3log-Linux-x86.deb

script:
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON .. 
     - make
     - ./rtdata_test
