language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - make
            - libcurl4-gnutls-dev
            # - gpsd
            - libqgpsmm-dev
            - libgps-dev
            - cppcheck
            - libcppunit-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
    - wget https://github.com/CosmicResearch/g3log/releases/download/1.3.2/g3log-1.3.2-Linux.2.deb
    - sudo apt-get install g3log-1.3.2-Linux.2.deb

script:
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON .. 
     - make
     - ./rtdata_test
