language: cpp

env:
  global:
    - LINUX_DIST=trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - make
            - libcurl4-gnutls-dev
            - gpsd
            - libqgpsmm-dev
            - libgps-dev
            - cppcheck
            - libcppunit-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157

script:
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON .. 
     - make
